language: ruby

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v
  - chmod +x entrypoints/docker-entrypoint.sh

install:
  - docker-compose build 

before_script:
  - docker-compose up -d
  - # The detached `up` also runs entrypoint — but because it's detached,
  - # bundle install doesn't finish before shell moves on to next commands.
  - docker ps

script:
  - docker-compose exec app bundle exec rake db:setup db:migrate test

after_script:
  - docker-compose down